apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-buildah
spec:
  serviceAccountName: default
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: task-buildah
      subPath: source
  taskRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/Aneesh-M-Bhat/resolvers-test.git
      - name: revision
        value: main
      - name: pathInRepo
        value: buildah.yaml
  params:
    - name: IMAGE
      value: "hub.docker.com/repository/docker/aneeshmbhat3719/test-buildah:latest"
    - name: TLS_VERIFY
      value: "false"
    - name: VERBOSE
      value: "true"
